### ISSUE TITLE
animation动画

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#10]
# ✅ animation动画

CSS中的动画可以通过 `animation` 触发. 类似于 `transition`, `animation` 也具有几个简写属性, 较为常用的有 `animation-name`, `animation-duration`, `animation-timing-function`, `animation-delay`。

**这些主要参数和 `transition` 类似, 可参考 👉 [transition过渡动画](https://github.com/Douc1998/CSS-Notes/issues/9)**

其中 `animation-name` 与 `transition-property` 可选参数不一样, `animation-name` 为具体的动画名称, 如自定义的 **`myAnimation`**

```SCSS
/* 关于 keyframes 关键帧的自定义动画myAnimation*/
@keyframes myAnimation{
    0%{background-color: lightblue;}
    30%{background-color: lightgreen;}
    60%{background-color: lightgray;}
    100%{background-color: black;}
}
```
`animation` 的所有参数及其说明如下所示：
参数|说明
|:-:|:-:|
animation-name | 指定要绑定到选择器的关键帧的名称
animation-duration | 动画指定需要多少秒或毫秒完成
animation-timing-function | 设置动画将如何完成一个周期
animation-delay | 设置动画在启动前的延迟间隔。
animation-iteration-count | 定义动画的播放次数。
animation-direction | 指定是否应该轮流反向播放动画。
animation-fill-mode | 规定当动画不播放时（当动画完成时，或当动画有一个延迟未开始播放时），要应用到元素的样式。
animation-play-state | 指定动画是否正在运行或已暂停。
- - - - - - - - - -
**小拓展 ⬇️**

> animation制作动画效果需要两步，**首先用关键帧声明动画**，**再用animation调用动画**.
> 
> **关键帧**的语法是以 `@keyframes` 开头，后面紧跟着动画名称`animation-name`。from等同于0%，to等同于100%。百分比跟随的花括号里面的代码，代表此时对应的样式.
>
> ```SCSS
> @keyframes animation-name{
>     from | 0%{}
>     n%{}
>     to | 100%{}
> }
> ```

---
参考文章：
🔗  [CSS3 animation（动画） 属性](https://www.runoob.com/cssref/css3-pr-animation.html)
🔗  [深入理解CSS动画animation](https://www.cnblogs.com/xiaohuochai/p/5391663.html)
