### ISSUE TITLE
CSS动态伪类

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#12]
# ✅ CSS动态伪类

我们常常会遇到一些 **基于事件的样式变化**, 如 "鼠标点击后样式改变"、"鼠标悬浮样式改变"等等.

CSS中存在一系列的 **动态伪类**, 如 `link`、`visited`、`hover`、`active`、`focus`, 下面将介绍这些伪类的属性和作用.

- [x] **`:link`**
访问链接的样式, 所以只要你是超链接, 且**未被访问过**, 则链接都会按照你设定的样式显示.

- [x] **`:visited`**
链接访问后的样式. 则**链接一旦被访问**, 则之后它的样式就会是你所设置的visited样式.

- [x] **`:hover`**
鼠标光标经过某一元素时的样式. **鼠标移入激活样式, 鼠标移出样式消失**

- [x] **`:focus`**
**适用于当一个焦点元素的状态设置**。例如, 用户点击文本框, 准备输入时,  文本框的`:focus`伪类将被触发; 又如用户点击了按钮之后, 会触发相应的样式. **值得注意的是，元素将保持获得焦点状态，除非用户点击其他的元素**.

- [x] **`:active`**
**适用于在元素被激活时**。例如，用户使用鼠标时，单击鼠标按钮和释放鼠标按钮之间的时间就是 `:active` 触发时机 (**注意: 是点击不放开的那段时间**)。

---
很显然, 如`hover`、`focus`、`active`三者不冲突, 可以结合使用, 从而实现更好的样式效果. 但是, 我们要 **把握好伪类的顺序**. 举个例子: ⬇

```SCSS
button:hover {
    background-color: green;
}

button:focus {
    background-color: blue;
}

button:active {
    background-color: red;
}

```

当你在进行交互时, 

+ **只需要鼠标仍然悬停在元素上, `:hover` 样式就会被触发 (除非不适用于当前伪类, 后续伪类才会生效)**. 
<br>

+ **当鼠标点击按钮不松开时, `:hover`失效, `:active` 样式会触发**.
<br>

+ **当鼠标移出按钮时, `:active`失效, `:focus` 会生效，因此会出现蓝色**。

模拟一次点击按钮行为：用户会首先悬停 (`:hover`) 在元素上，然后点击按下，激活元素 (`:active`), 松开按钮后，按钮获得焦点 (`:focus`).

---
参考文章：
🔗  [聊聊 :hover , :focus 和 :active 的适用场景](https://zhuanlan.zhihu.com/p/52340877)
🔗  [【重识 HTML + CSS】CSS 伪类、伪元素](https://blog.csdn.net/weixin_43734095/article/details/117116525)
