### ISSUE TITLE
一种float居中的方式

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#2]
# ✅ 一种float元素水平居中方法

当我们设置 `float: left` 或者 `float: right` 时, 元素会 **靠左** / **靠右**, 那么如何在**必须**使用 `float` 布局时让 **元素居中** 呢?

```SCSS
.father {
    position: relative;
    float: left;
    left: 50%;
    // overflow: hidden;  overflow不可设置为hidden, 否则无效
    .son {
        position: relative;
        float: left;
        right: 50%;
        // left: -50%;  right 50% 等同于 left -50%
    }
}
```
**原理如下图所示:**

> + `.wrap` **左浮动50%**, 相当于它的 **左边线** 位于 `.out` 的 **中线** 位置.
> + `.inner` **左浮动-50%**, 相当于以`.out`的 **中线为基准** 左移一半.
> +  `.inner` 里的`position: relative`，就是为了 让 `.inner` 以 `.wrap` 为基准左移而不是 `.out` 。

![示意图](https://user-images.githubusercontent.com/62340860/159828075-839399eb-c6dc-481f-98aa-acd520ca2a21.png)

---
参考资料: 
🔗  <a href="https://blog.csdn.net/oscar92420aaa/article/details/51362435" target="_blank">水平居中position--评论内容</a>
🔗  <a href='https://www.jb51.net/article/70767.htm' target='_blank'>css如何让浮动元素水平居中</a>
