### ISSUE TITLE
预处理器 Sass

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#25]
在之前的开发过程中一直使用的是 `Sass`，所以趁着机会，写一个简单地介绍和总结。

# CSS 预处理器

虽然我们可以使用 CSS 来实现一系列比较复杂的需求，但是随着需求愈发复杂、项目工程变大、样式增多，使用和维护 CSS 定义的样式也会让我们感到十分困难。此外，有一些更加灵活、动态的需求，我们没办法通过 CSS 来实现，而需要借助 JS 来实现，比如基于 `if` 判断设置不同样式，或者使用 `for` 给列表里元素属性设置一些递进关系。

因此，我们引入**CSS预处理器**，也就是说在我们和 CSS 样式之间，增加一个环节：**预处理器**。预处理器能够提供一些便捷的功能，如：**嵌套**、**循环**、**混入**、**选择器**、**函数**等。我们可以在预处理器中基于提供的方法更便捷地书写样式，至于转译为 CSS，那就不是我们的任务了，预处理器会帮我们实现。

如今已经有很多款预处理器了，如`Sass`、`Less`、`Stylus`。

# Sass

`Sass 3` 之后引入了新语法，其语法也完全兼容了 `CSS 3`，并且继承了 `Sass` 的强大功能。因此，我们这里就主要介绍 `Sass 3`，也称为 `Scss`，文件后缀名也由原来的 `.sass` 变为了 `.scss`。

## 声明变量
在 `Sass` 中，我们可以**通过 `$` 符号来声明变量**，并在变量名后使用 `:` 进行赋值，之后我们就可以直接用变量名才给一些属性赋值，不再需要每次重复写了。举个例子：

```css
/* 声明变量 */
$primary-color: red;

.body {
  color: $primary-color;
}
```
但是，变量也有**全局变量**和**局部变量**之分，这和 JS 的作用域是相同的。我们在局部作用域中声明的变量，不能被外部访问到。举个例子：

```css
/* 全局变量 */
$global-color: red;

.body{
    color: $global-color;
}

.box{
    /* 局部变量 */
    $local-color: blue;
    color: $local-color;
}
```
上面例子中，我们不能在 `.body` 中使用 `.box` 内部声明的 `local-color` 变量。

## 嵌套
在 `Sass` 中，我们可以使用**嵌套**语法，使得代码逻辑性更强，写起来也更方便。我们先看一个 CSS 语法：

```css
#header {
  color: black;
}
#header .nav {
  font-size: 12px;
}
#header .logo {
  width: 300px;
}
```
上面的代码我们使用 sass 嵌套就可以轻松地写为：

```scss
#header {
  color: black;
  .nav {
    font-size: 12px;
  }
  .logo {
    width: 300px;
  }
}
```
有上面代码一眼可知，`nav` 和 `logo` 的样式规则仅在 `header` 内部生效。很显然这种书写方式更便于理解，也更加便捷，对于后期维护也更加方便。

## 选择器

CSS 的基本选择器在 Sass 中同样适用，比如 `>`（这是 CSS 3中特有的属性，`A > B**` 表示选择 A 元素的**所有**子 B 元素，而 `A > B` 表示只选择 A 元素后的**一代**里的子 B 元素）。sass的写法如下：

```scss
/* > 选择器 */
.container{
  > .left-area{
   ...
 }
}
```

此外，sass 还提供了**父选择器**（`&`)，我们可以在嵌套中使用 `&` 来引用父元素，并给他添加一系列样式，如：
```scss
.container{
  &.right-area{
   background-color : red
 }
}
```
上面的代码等同于：

```css
.container.right-area {
  background-color : red
}
```
我们还可以给父选择器添加一系列伪类或伪元素，如：`& : hover` 、`& :: after`。

## 混入（Mixin）
Sass 另一个了不起的特性就是**它能够将可重用的样式打包在一起，并允许根据需要将样式导入到另一个样式块中，从而减少代码中的冗余**。我们只需要使用 `@mixin` 声明某个 CSS 样式即可，如下：

```scss
@mixin button {  
    font-size: 1em;  
    padding: 0.5em 1.0em;  
    color: #fff;  
}
```

此时我们已经打包好了一个名为 `button` 的样式，下面我们需要在另一个样式块中，使用 `@include` 引入该打包样式的名称即可：

```scss
.button-green {  
    @include button;  
    background-color: green;  
}
```

上面的代码等效的 CSS 代码为：

```css
.button-green {  
    font-size: 1em;  
    padding: 0.5em 1.0em;  
    color: #fff;  
    background-color: green;  
}
```

使用 `mixin` 的另一种强大功能就是我们可以**传入参数**，就像 JS 中的函数一样，我们可以声明一个全局变量并将其设置为 `mixin` 的一个参数。下面我们更新上面的 `button` 模块，给他增加了名为 `background` 的参数。

```scss
@mixin button($background) {  
    font-size: 1em;  
    padding: 0.5em 1.0em;  
    color: #fff;  
    background: $background;  
}
```
注意到参数被设置为一个变量并成为 `backround` 属性的值。如果我们想创建一个绿色的按钮，那么就可以使用以下代码：
```scss
.button-green {  
    @include button(green);  
}
```
你可能会好奇如果在定义 `mixin` 时定义了参数，但是在 `@include` 调用时没有传递参数会发生什么。

这种情况下你会收到一个编译错误的提示。同时我相信这种情况一定不是你想看到的。你可以通过在 `mixin` 中定义参数的时候给它设置一个**默认值**，从而来避免这种错误。

```scss
@mixin button($background: green) {  
    font-size: 1em;  
    padding: 0.5em 1.0em;  
    color: #fff;  
    background: $background;  
}
```
现在如果你在调用的时候忘记传递参数值:
```scss
.button-green {  
  @include button;  
}
```
你的代码将会使用你设置的参数默认值来解析，在这个例子中也就是green这个值。
```css
.button-green {  
    font-size: 1em;  
    padding: 0.5em 1.0em;  
    color: #fff;  
    background: green;  
}
```

## 函数
函数是 Sass 功能的重要组成部分，它们允许我们定义可在整个样式表中重用的复杂操作。有很多内置的 Sass 函数可供我们使用，可以查看[官方文档](https://sass-lang.com/documentation/at-rules/function)进一步了解一些常用的函数，也可以去看看这篇[文章](https://juejin.cn/post/7033786360162942984)。

我们也可以定义自己的 Sass 函数，要实现函数的声明和返回内容和 JS 也是相似的。我们需要使用 `function` 和 `return`两个指令来实现，如：
```scss
@function 函数名(形参) {
  @return;
}
```
使用时直接调用函数名即可，但是要注意的是：**返回的内容需要我们通过 `#{}` 来进行取值**。
```scss
/* 自定义 getWidth 函数 */
@function changeWidth($w) {
  @return $w * 2;
}

.main{
  max-width: #{changeWidth(20)} px;
}
```
编译后的结果为：
```scss
.main {
  max-width: 40px;
}
```

### if()
`if()` 是 Sass 的一个**内建函数**，与之相似的 `@if` 则是一个**内建指令**。`if()`常用来**做条件判断并返回特定值**，举个例子：
```scss
@mixin test($condition) { 
  /* 局部变量 color，根据 if 判断 */
  $color: if($condition, blue, red); 
  color:$color 
}
  
.firstClass { 
  @include test(true); 
} 
 
.secondClass { 
  @include test(false); 
}
```

上面代码的编译结果为：

```scss
.firstClass {
  color: blue; 
} 
.secondClass { 
  color: red; 
}
```

在上面的例子中，`if()` 函数内的三个参数分别代表：**测试条件**、**测试成功返回值**，**测试失败返回值**（除了 `false` 和 `null` 之外的所有测试条件都被视为测试成功），这种逻辑实际上就是我们 JS 中常用的判别式。

如果使用数字作为上述示例的条件，同样会返回测试成功的值：
```scss
.firstClass { 
  @include test(1); 
}
```
### @if
`@if` 后跟一个表达式，如果表达式的结果为 `true`，则返回特定的样式，示例如下：
```scss
@mixin test($weight) { 
  color: white; 
  /* 判别式 决定 {}*/
  @if $weight == bold { 
        font-weight: bold;
   } @else{
        font-weight: lighter;
   }
} 

.test1 { 
  @include txt(none); 
} 

.test2 { 
  @include txt(bold); 
}
```
上面代码的编译结果为：
```scss
.txt1 { 
  color: white; 
  font-weight: lighter; 
} 

.txt2 { 
  color: white; 
  font-weight: bold; 
}
```

### @for
`@for` 指令常用于循环输出。`@for` 有两种使用方式：`from start through end` 和 `from start to end`，两者的区别在于：

+ 前者遍历的范围是 [start, end]
+ 后者的遍历范围是 [start, end-1]。

在 `@for` 循环中使用一个固定变量来替代遍历到的元素。如果你想实现从大到小的遍历，只需让 start 大于 end 即可。下面是 `@for` 的一个简单示例：

```scss
@for $i from 1 through 4 { 
  .col-#{$i} { 
    width: #{100/4 * $i}%;
  } 
}
```
使用上面的这个例子，我们可以创建一套简单的栅格系统，编译结果如下:
```scss
.col-1 { 
  width: 25%; 
} 
.col-2 { 
  width: 50%; 
} 
.col-3 { 
  width: 75%; 
} 
.col-4 { 
  width: 100%; 
}
```

## 总结
上面简要概括了一些关于 `Sass` 的特点、语法和使用场景，可以满足大多数日常场景需求（可能因为我学校里做的项目比较简单的缘故），如果问题复杂，最好还是去看[官方文档](https://sass-lang.com/documentation/)。

## 参考
[如何使用SASS编写可重用的CSS](https://juejin.cn/post/6844904039503642637)
[Sass 官方文档](https://sass-lang.com/documentation/)
