### ISSUE TITLE
flex 布局下子元素的 order 顺序

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#26]
# flex 布局下子元素的 order 顺序

此时有一个 `display: flex` 布局的 `<div>`，其下有若干子元素 `content1`、`content2`、`content3`、`content4`。我们如果想决定这四个 content 的顺序，最简单的方法就是在 html 中按照我们需要的顺序定义即可。

那么如果我们需要在 js 中调整这四个元素的顺序该怎么办呢？这就需要使用到弹性布局子元素的 `order` 属性。

MDN 对 order 的解释如下：

> CSS order 属性规定了弹性容器中的可伸缩项目在布局时的顺序。**元素按照 order 属性的值的增序进行布局**。拥有相同 order 属性值的元素按照它们在源代码中出现的顺序进行布局。

> **备注**： order 仅仅对元素的**视觉顺序 (visual order) 产生作用，并不会影响元素的逻辑或 tab 顺序**。 order 不可以用于非视觉媒体，例如 speech。

由上可知，我们使用 `order` 可以修改元素在视觉上的顺序，但是并**不会影响元素在 DOM 树中的顺序**。

---

举个例子：

```scss
#myDiv {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
}

#content1, #content2, #content3, #content4 {
    height: 50px;
    width: 50px;
}

#content1 {
    background-color: yellowgreen;
}

#content2 {
    background-color: orange;
}

#content3 {
    background-color: pink;
}

#content4 {
    background-color: skyblue;
}
```

我们有一个弹性盒子 `myDiv`，其内部有四个不同颜色的盒子 `content1 - 4`。

```html
<div id="myDiv">
    <div id="content1">1</div>
    <div id="content2">2</div>
    <div id="content3">3</div>
    <div id="content4">4</div>
</div>
```

当我们不使用 order 来布局顺序时，这四个盒子的 order 属性默认都为 0，因此按照 MDN 中说的**order 相同的元素会按照 html 中定义的顺序来排布**：

<img width="649" alt="截屏2023-05-09 21 03 01" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/52d5fafd-b745-484e-894f-31263af6efb6">

如果我们给每个 content 盒子添加 `order` 属性，其值分别为 1、2、3、4

```css
#content1 {
    order: 1;
    background-color: yellowgreen;
}

#content2 {
    order: 2;
    background-color: orange;
}

#content3 {
    order: 3;
    background-color: pink;
}

#content4 {
    order: 4;
    background-color: skyblue;
}
```
其排布顺序如下：

<img width="640" alt="截屏2023-05-09 21 16 45" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/a9cdc09f-9a4f-40a8-95c3-d256daafeb60">

因此，我们可以根据需求，在 JS 中获取 DOM 元素并修改其 `order` 属性，就可以动态地修改子元素的顺序。如：添加一个 `button` 按钮，点击该按钮可以让 1  2  3  4 的顺序变为 4  3  2  1。

```js
// 获取 dom 元素
let content1 = document.querySelector('#content1');
let content2 = document.querySelector('#content2');
let content3 = document.querySelector('#content3');
let content4 = document.querySelector('#content4');

// 点击事件
function move() {
    content1.style.order = 4;
    content2.style.order = 3;
    content3.style.order = 2;
    content4.style.order = 1;
}
```

点击该按钮后，效果如下：

<img width="645" alt="截屏2023-05-09 21 17 31" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/eb83dac6-34dc-48a3-90e9-3d4fc2f506be">

为了验证文档中说 “**只影响视觉顺序，不会影响 DOM 中顺序**”，我们还是用上面的例子。html 中创建的元素是按照 content 1 - 4 的顺序创建的，我们在 button 的 `move` 方法中添加 
```js
function move() {
    content1.style.order = 4;
    content2.style.order = 3;
    content3.style.order = 2;
    content4.style.order = 1;
    console.log(document.querySelector('#myDiv').childNodes); // 输出查看 myDiv 子元素的 dom 顺序
}
```
我们输出 `myDiv` 的 `childNodes` 查看：
<img width="507" alt="截屏2023-05-09 21 20 53" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/dbeebd1a-0f8d-4a1f-aa8e-a710018c7047">

由上可知，order 并不会修改 DOM 树中元素的顺序，只是修改视觉效果。

最后，如果我们想让切换顺序变得更加平滑，也可以使用 `transition` 指定 `order` 属性来创建平滑动画。
