### ISSUE TITLE
选择器：伪类 focus-within

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#27]
# 选择器：伪类 focus-within

假设有一个场景：**一个盒子 myiDv 中有一个 input 输入框，当我 `focus` 该输入框时，希望同时能够让该盒子也高亮起来**（即：盒子myDiv 原本的背景颜色为白色，但是 focus input 时能够修改 myDiv 的背景颜色）。效果如下：

<img width="239" alt="截屏2023-05-10 12 18 47" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/5b6c7e97-e936-4358-9da3-f6407c7a4d55">

---
为了完成这个场景需求，先简单定义 `myDiv` 和 `input` 等元素及其样式，如下：

```html
<div class="myDiv">
    <span>name</span>
    <input must/>
</div>
```
```scss
.myDiv {
    width: 200px;
    padding: 10px 10px;
    background-color: white;
    display: flex;
    justify-content:space-between;
}

input{
    width: 100px;
}
```
效果如下：

<img width="258" alt="截屏2023-05-10 12 06 47" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/db90bd42-afaf-4095-85f1-95d5a62100a9">

`myDiv` 的 dom 样式结构为：

<img width="221" alt="截屏2023-05-10 12 07 32" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/12966f0b-e6f0-4aae-b7f5-8a378478af0d">

准备工作已就绪，为了完成上面场景中的需求，我们会想到使用伪类 `:focus`，如：

```scss
input:focus{
    background-color: rgb(196, 235, 250);
}
```
但实际效果并不是我们需要的那样：

<img width="239" alt="截屏2023-05-10 12 09 29" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/6d44a226-b980-4d8f-88af-9202ccb50c79">

这个 `:focus` 修改的背景颜色是 `<input>` 标签的背景颜色，而不是 `myDiv` 的背景颜色。

---

## focus-within

那么该怎么办呢？这里就需要提到另一个伪类功能：**`:focus-within`**。

MDN 中对 `:focus-within` 的介绍如下：

> :focus-within 表示当元素或其任意后代元素被聚焦时，将匹配该元素。换言之，它表示 `:focus` 伪类匹配到该元素自身或它的后代时，该伪类生效。（这也包括 shadow 树中的后代元素。）

简而言之，**`:focus-within` 包含了 `:focus` 的功能，即当前元素被 focus 时会触发其内部内容。此外，如果当前元素的子元素或者任意后代元素被 focus 时，当前元素都会触发 `:focus-within` 中的内容**。

因此，我们只需要修改一下 css 代码：

```scss
.myDiv {
    width: 200px;
    padding: 10px 10px;
    display: flex;
    justify-content:space-between;
}
/* 关键代码：给 myDiv 增加 focus-within 伪类选择器即可 */
.myDiv:focus-within{
    background-color: rgb(196, 235, 250);
}
input{
    width: 100px;
}
```

此时，当我们再点击 input 输入框时，就能够触发 `myDiv` 的 `:focus-within` 的事件，修改其背景颜色，效果如下：

<img width="239" alt="截屏2023-05-10 12 18 47" src="https://github.com/Douc1998/CSS-Notes/assets/62340860/5b6c7e97-e936-4358-9da3-f6407c7a4d55">
