### ISSUE TITLE
flex布局

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#5]
# ✅ flex布局

`flex布局` 即 **弹性布局**, 它可以自动弹性伸缩, 从而适应不同大小的屏幕, 是一种好用且便捷的布局方式.

```SCSS
.box {
    display: flex;
    flex-direction: row | row-reverse | column | column-reverse;
    flex-wrap: nowrap | wrap | wrap-reverse;
    justify-content: flex-start | flex-end | center | space-between | space-around;
    align-items: flex-start | flex-end | center | baseline | stretch;
    align-content: flex-start | flex-end | center | space-between | space-around | stretch;
}
```
<br>

**`flex-direction`、 `justify-content`、 `align-item` 是三个较为常用的参数, 下面将详细介绍**

<br>

- [x] `flex-direction` 决定了元素的**排列方式**, 如 **行 / 列**.

![image](https://user-images.githubusercontent.com/62340860/160139633-711c34af-d2bc-4dae-8374-05274b58aae5.png)

- [x] `justify-content` 决定了元素**在主轴上的对齐方式**。

![image](https://user-images.githubusercontent.com/62340860/160139781-e9e59f39-ec1f-4006-b8c5-34016580a67d.png)

- [x] `align-items` 决定了元素**在交叉轴上如何对齐**。

![image](https://user-images.githubusercontent.com/62340860/160140748-0e761df1-dcae-4884-90f1-f32af135f5e0.png)

---
参考资料: 
🔗  <a href="https://www.runoob.com/w3cnote/flex-grammar.html" target="_blank">Flex 布局语法教程</a>
