### ISSUE TITLE
display的几种方式

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#8]
# ✅ display的几种方式

CSS中的 `display` 是一个很常用的属性, 顾名思义,即 **布局**. 
`display` 有几种较为常用的布局, **如`none`、`inline`、`block`、`inline-block`、`flex`等**. 

---
- [x] **`none`**

显而易见, `none`即无, 当我们给一个元素的`display`属性设置为`none`时, 这个元素将 **不会显示**.
```SCSS
<style>
    .none-content{
        display: none;
        border-width: 5px;
        border-color: blue;
        border-style: solid;
    }
</style>
<div class='none-content'>I am a none element</div>
```
> 看不见`display: none`的元素.

---
- [x] **`inline`**

`inline` 布局即**行内布局**, 它的大小将完全 **取决于其内部元素的大小**. 因此, 我们给设置为 `display: inline`的元素设置 `width`和`height`时是不管用的, 实际上它的长宽会设置为 **`auto`**
```SCSS
<style>
    .inline-content{
        display: inline;
        height: 1000px;
        width: 1000px;
        border-width: 5px;
        border-color: blue;
        border-style: solid;
    }
</style>
<div class='inline-content'>I am an inline element</div>
```
> 至于如何给 `inline` 元素设置固定的宽高, 可以考虑使用 `float` 或 `position` / `flex` 实现.

---
- [x] **`block`**

`block` 即为 **盒子**, 当一个 `div` 被设置为 `block` 时, 将会变为**块级元素**. 然而, 相比于 `inline` 不能直接设置宽高, `block` 可以通过设置 `height` 和 `width` 改变盒子的大小, **其内部元素也会根据盒子大小进行排布、换行等**.
```SCSS
<style>
    .block-content{
        display: block;
        height: 100px;
        width: 100px;
        border-width: 5px;
        border-color: red;
        border-style: solid;
    }
</style>
<div class='block-content'>I am a block element1</div>
<div class='block-content'>I am a block element2</div>
```
---
- [x] **`inline-block`**

`inline-block` 即是 `inline` 和 `block` 的结合 => 它既能够使得元素成为 **行内元素**, 可以和其他行内元素共享一行; 也可以**成为块级元素**, 设定宽高和`left`、`right`、`top`、`bottom` 来设定内部样式.
```SCSS
<style>
    .inline-block-content{
        display: inline-block;
        height: 50px;
        width: 200px;
        border-width: 5px;
        border-color: green;
        border-style: solid;
    }
</style>
<div class='inline-block-content'>I am an inline-block element1</div>
<div class='inline-block-content'>I am an inline-block element2</div>
```
> `inline-block` 布局适用于很多需求, 如 **同行里排列按钮**等. 因此, `inline-block` 的特点可以总结为：**外部看来是"流"，但是自身确实一个"块"**.

---
- [x] **`flex`**

`flex`布局在先前已经单独写了一个issue进行讲解,详情见 👉 [flex布局](https://github.com/Douc1998/CSS-Notes/issues/5)

---
- [x] **`float`**
`float` 不是 `display` 中的一种布局样式, 但也是一种重要的**布局属性**, 先前已单独写了一个issue进行讲解, 详情见 👉 [float浮动概念](https://github.com/Douc1998/CSS-Notes/issues/6)

---
- [x] **总结**

**解释一下 `display` 的几个常用的属性值，`inline` ， `block`， `inline-block`**

+ **`inline`**:
> + 使元素变成行内元素, 拥有行内元素的特性, 即可以与其他行内元素共享一行，不会独占一行. 
> + 不能更改元素的 `height`, `width`的值，大小由内容撑开. 
> + 可以使用 `padding`, `margin` 的 `left` 和 `right` 产生边距效果，但是 `top` 和 `bottom` 就不行.

+ **`block`**:
> + 使元素变成块级元素, 独占一行, 在不设置自己的宽度的情况下, 块级元素会默认填满父级元素的宽度. 
> + 能够改变元素的 `height`, `width`的值. 
> + 可以设置 `padding`, `margin` 的各个属性值, `top`, `left`, `bottom`, `right` 都能够产生边距效果.

+ **`inline-block`**:
> + 结合了 `inline` 与 `block` 的一些特点，结合了上述 `inline` 的第1个特点和 `block` 的第2, 3个特点.

---
参考文章：
🔗  [CSS---display详解](https://www.cnblogs.com/moxuexiaotong/p/10071072.html)
