### ISSUE TITLE
transition过渡动画

### ISSUE THREAD

**Issue by WwwHhhYran** [Douc1998/CSS-Notes#9]
# ✅ transition 过渡动画

`transition` 属性可以设置当前元素的 **过渡** 效果, 从而实现 **动画** 效果, 是一个十分常用的属性.

`transition` 有 **四个简写属性**, 分别是:
+ `transition-property`
+ `transition-duration`
+ `transition-timing-function`
+ `transition-delay`

下面讲详细介绍这四个属性的作用...

- [x] **`transition-property`**

```SCSS
transition-property: none | all | property;
```
`transition-property` 即 **发生过渡效果的属性名称**.
value | Description
:-:|:-:
none | 没有属性需要过渡
all | 所有属性都会实现该过渡效果
property | 定义应用过渡效果的CSS属性名称列表，列表以逗号分隔。
```SCSS
<style>
    .green{
        display: inline-block;
        width: 200px;
        height: 200px;
        background-color: green;
        /* 关键代码 指定边框棱角的radius变化 */
        transition: border-radius 0.5s ease 0s;
    }
    /* 当鼠标移入时, radius变为80% */
    .green:hover{
        border-radius: 80%; 
    }

    .blue{
        display: inline-block;
        width: 200px;
        height: 200px;
        background-color: blue;
        /* 关键代码 所有属性都会按照该动画参数变化 */
        transition: all 0.5s ease 0s;
    }
    /* 当鼠标移入时, radius变为80%, 并缩小到0.5倍 */
    .blue:hover{
        border-radius: 80%; 
        transform: scale(0.5);
    }
</style>
<div class='green'></div>
<div class='blue'></div>
```

---
- [x] **`transition-duration`**

```SCSS
transition-duration: time;
```
`transition-duration` 即 **完成过渡效果需要的时间**. 

**注意**: 如果不设置 `duration` 属性的话, 时间为0, 则不会显示过渡动画.

---
- [x] **`transition-timing-function`**
```SCSS
transition-timing-function: linear | ease | ease-in | ease-out | ease-in-out | cubic-bezier(n, n, n, n);
```
`transition-timing-function` 即 **过渡动画的“缓动函数”**. 就是过渡的时候 **速度怎么变**, 可以是线性不变的, 也可以是先快后慢等等.

![image](https://user-images.githubusercontent.com/62340860/160963856-9bd1840f-a2b0-4236-a4f4-c72885aad964.png)

其中, cubic-bezier(n, n, n, n)是可以自己设定值的 **贝塞尔曲线**, 如`cubic-bezier(.19, .72, .83, .27)`

🔗 **贝塞尔曲线取值可视化网页** 👉 [cubic-bezier](https://cubic-bezier.com/)

```SCSS
<style>
    .linear{
        display: inline-block;
        width: 50px;
        height: 50px;
        background-color: green;
        /* 关键代码 线性函数 */
        transition: border-radius 1s linear 0s;
    }
    .linear:hover{
        border-radius: 80%; 
    }

    .ease{
        display: inline-block;
        width: 50px;
        height: 50px;
        background-color: blueviolet;
        /* 关键代码 ease函数 */
        transition: border-radius 1s ease 0s;
    }
    .ease:hover{
        border-radius: 80%; 
    }

    .ease-in{
        display: inline-block;
        width: 50px;
        height: 50px;
        background-color: red;
        /* 关键代码 ease-in函数*/
        transition: border-radius 1s ease-in 0s;
    }
    .ease-in:hover{
        border-radius: 80%; 
    }

    .ease-out{
        display: inline-block;
        width: 50px;
        height: 50px;
        background-color: grey;
        /* 关键代码 ease-out函数*/
        transition: border-radius 1s ease-out 0s;
    }
    .ease-out:hover{
        border-radius: 80%; 
    }

    .ease-in-out{
        display: inline-block;
        width: 50px;
        height: 50px;
        background-color: gold;
        /* 关键代码 ease-in-out函数*/
        transition: border-radius 1s ease-in-out 0s;
    }
    .ease-in-out:hover{
        border-radius: 80%; 
    }

    .bezier{
        display: inline-block;
        width: 50px;
        height: 50px;
        background-color: rgba(50, 250, 255, 0.75);
        /* 关键代码 cubic-bezier函数*/
        transition: border-radius 1s cubic-bezier(.19, .72, .83, .27) 0s;
    }
    .bezier:hover{
        border-radius: 80%; 
    }
</style>
<div class='linear'></div>
<div class='ease'></div>
<div class='ease-in'></div>
<div class='ease-out'></div>
<div class='ease-in-out'></div>
<div class='bezier'></div>
```

---
- [x] **`transition-delay`**

`transition-delay` 属性顾名思义, 即 **延迟多久后触发**.

**注意**: 如果不设置 `delay` 属性的话, 时间为0s, 则立刻触发.

---
参考文章：
🔗  [CSS3中的transition属性详解](https://www.cnblogs.com/afighter/p/5731293.html)
🔗  [CSS3 transition属性](https://www.runoob.com/cssref/css3-pr-transition.html)
